sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IjsBMIJwGIGr0y0hZyDrTIUuCsrWaH/KJV7QNz06tKuVZ/tVy2/2FN/rxkWz9DfjhkgDAbBy0tH7xWVQFrJiJIbsqh11MOdklFmPivxpHk4LSh3FARX4AwTOmkRA7wHt8wYcFgPscqFqLaxfOTL857o66OmNrA8kUA0wALtHjPPwFuoiGNxHh7vXYghe3f+q9GfsrAxL6BOz6bexo5a/UL1lgZkmYhAGFsKj57zOlFX1E/tfK4+xNu5Dk1lArc+/mnbeuHtKzlz3typUMsbCmfBfzd6qhqttl+Wa6kFtDSqS+qZqmz3ou57fLtwYJURUAXCgPiRst+hrg+lfJNHIT2tVYyIKb6xmrJoJqlmyjGmof5iBQ/iwPTKgyDlWAh9j4OrNRKqRpCAZcM9KLoAEz6xK1l5kT0JscJKr/zJx/vOhV9MdqgQJw6T5JDttSpQYQoMfqoiyJoH9vvL0zAzIPTqrmPhkNLdA9XmvwHT2mMmzYeP6AY5SCo8PYiYsJVl7NZyGbAHbtt+lFCkF4wgAun7JyvD2JlV2YtF0jUVrzZe/g5MaxlP06KGdeFYmCa0Wr4m5P2H/ZxytQDsLrXo1mvgzPpND70/YcxrgY/+YFyki22nHHZe8YnvWVJw80GXkP7O+bJ6LVOIdXRkObUnCfZ4dtOeW038bb6ac5Aho9CI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Return_3075
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy